INSERT INTO products( user_id, title, description, thumbnail_photo, main_photo, brand,
size, price, feature)
VALUES
( 1, 'Air Jordan 1 Retro High OG UNC (2021)', 'This AJ 1 features a similar design to the “UNC Patent” 1s that released in February of 2019, only this time the colorway receives a full leather treatment. This sneaker released in August of 2019', 'https://image.goat.com/1000/attachments/product_template_pictures/images/008/654/832/original/31395_00.png.png', 'https://image.goat.com/1000/attachments/product_template_pictures/images/008/654/832/original/31395_00.png.png', 'Nike', 9, 550, false ),

( 1, 'Nike Dunk Low Retro White Black (2021)', 'From the school-spirited College Colors Program to the vibrant Nike CO.JP collection, Nike Dunks have seen many colorways since the design’s inception in 1985. But with each new colorway, the Dunk’s classic color-blocking has remained in some capacity. Nike put its timeless color-blocking to work with the Nike Dunk Low Retro White Black.', 'https://image.goat.com/750/attachments/product_template_pictures/images/051/507/240/original/719082_00.png.png', 'https://image.goat.com/750/attachments/product_template_pictures/images/051/507/240/original/719082_00.png.png', 'Nike', 8, 350, false ),

( 1, 'Nike Dunk Low Pink Pearl', 'Nike delivered a warm-paletted women’s exclusive with the Nike Dunk Low Retro Orange Pearl. The Orange Pearl follows traditional Nike Dunk color-blocking, a design with panels of the shoe’s upper saturated by a designated color.', 'https://image.goat.com/1000/attachments/product_template_pictures/images/050/396/292/original/721459_00.png.png', 'https://image.goat.com/1000/attachments/product_template_pictures/images/050/396/292/original/721459_00.png.png', 'Nike', 9, 100, false ),

( 1, 'Adidas Yeezy 500 Black', 'Kanye is back, this time with a brand new colorway of the Yeezy 500. Keeping it monochromatic, this pair is covered entirely in one color: utility black. Like other Yeezy 500s, this pair features a suede upper with mesh paneling. In addition, the midsole utilizes adidas’ Adiprene cushioning technology. ', 'https://image.goat.com/1000/attachments/product_template_pictures/images/012/750/775/original/315071_00.png.png', 'https://image.goat.com/1000/attachments/product_template_pictures/images/012/750/775/original/315071_00.png.png', 'Adidas', 7, 450, true ),

( 1, 'New Balance 550 White Red', 'The New Balance 550 ‘White Team Red’ showcases a simple palette on the vintage hoops shoe originally released in 1989. The low-top makes use of a layered white leather upper, accented with micro-perforated detailing and contrasting red accents throughout. The latter includes a raised ‘N’ logo on the quarter panel and a basketball graphic on the woven tongue. A durable rubber outsole maintains the throwback aesthetic, featuring flex grooves for a smooth ride.', 'https://image.goat.com/1000/attachments/product_template_pictures/images/048/707/967/original/708099_00.png.png','https://image.goat.com/1000/attachments/product_template_pictures/images/048/707/967/original/708099_00.png.png', 'New Balance', 8, 240, true ),

( 1, 'Nike Sacai Waffle LD White Nylon', 'Launching in March 2020, the Sacai x LDWaffle 'White Nylon' is the neutral follow-up to one of Nike’s most sought-after sneaker collaborations from 2019. The hybrid silhouette, combining the Nike LDV and Waffle Racer, features a white nylon upper with leather and suede overlays at the toe and heel. The Swoosh, laces and tongue are similarly double layered, while an elongated midsole adds to the sneaker’s eye-catching look.', 'https://image.goat.com/1000/attachments/product_template_pictures/images/033/924/948/original/541509_00.png.png','https://image.goat.com/1000/attachments/product_template_pictures/images/033/924/948/original/541509_00.png.png', 'Nike', 10, 440, false ),

( 1, 'Air Jordan 6 Retro OG Carmine 2021', 'The Air Jordan 6 Carmine returned in its original form in 2021. The nearly 20-year-old colorway first made its appearance in 1991 during Michael Jordan’s ’91-’92 season and brought in a new form of color blocking to the signature silhouette.', 'https://image.goat.com/1000/attachments/product_template_pictures/images/050/395/648/original/632801_00.png.png','https://image.goat.com/1000/attachments/product_template_pictures/images/050/395/648/original/632801_00.png.png', 'Air Jordan', 8, 340, false ),

( 1, 'Adidas Yeezy Boost 350 V2', 'First released on April 29, 2017, the Yeezy Boost 350 V2 ‘Cream White’ combines a cream Primeknit upper with tonal cream SPLY 350 branding, and a translucent white midsole housing full-length Boost. Released again in October 2018, this retro helped fulfill Kanye West’s oft-repeated ‘YEEZYs for everyone’ Twitter mantra, as adidas organized the biggest drop in Yeezy history by promising pre-sale to anyone who signed up on the website. Similar to the first release, the ‘Triple White’ 2018 model features a Primeknit upper, a Boost midsole and custom adidas and Yeezy co-branding on the insole.', 'https://image.goat.com/1000/attachments/product_template_pictures/images/014/822/680/original/116662_00.png.png','https://image.goat.com/1000/attachments/product_template_pictures/images/014/822/680/original/116662_00.png.png', 'Adidas', 8, 440, true );

